CREATE TABLE IF NOT EXISTS articles (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  content TEXT NOT NULL,
  model TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
